## Practise Notebook 1

In [1]:
#load data
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('melb_data.csv')
data.head()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.7996,144.9984,Northern Metropolitan,4019.0
1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.8079,144.9934,Northern Metropolitan,4019.0
2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.8093,144.9944,Northern Metropolitan,4019.0
3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,3067.0,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.7969,144.9969,Northern Metropolitan,4019.0
4,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,3067.0,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.8072,144.9941,Northern Metropolitan,4019.0

In [3]:
data.tail()

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,3150.0,...,2.0,2.0,652.0,NaN,1981.0,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392.0
13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,3016.0,...,2.0,2.0,333.0,133.0,1995.0,NaN,-37.85927,144.87904,Western Metropolitan,6380.0
13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,3016.0,...,2.0,4.0,436.0,NaN,1997.0,NaN,-37.85274,144.88738,Western Metropolitan,6380.0
13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,3016.0,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,3013.0,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0

In [4]:
data.loc[-1:,'Address']

0            85 Turner St
1         25 Bloomburg St
2            5 Charles St
3        40 Federation La
4             55a Park St
               ...
13575        12 Strada Cr
13576       77 Merrett Dr
13577         83 Power St
13578        96 Verdon St
13579          6 Agnes St
Name: Address, Length: 13580, dtype: object

In [5]:
data_drop = data.dropna(axis=0)

In [26]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [7]:
#setting target values to predict
y = data_drop.Price

In [8]:
features = ['Rooms', 'Bathroom', 'BuildingArea','Lattitude', 'Longtitude','Distance', 'YearBuilt','Landsize']

In [9]:
x = data_drop[features]

In [10]:
x.describe()

,Rooms,Bathroom,BuildingArea,Lattitude,Longtitude,Distance,YearBuilt,Landsize
count,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000,6196.000000
mean,2.931407,1.576340,141.568645,-37.807904,144.990201,9.751097,1964.081988,471.006940
std,0.971079,0.711362,90.834824,0.075850,0.099165,5.612065,38.105673,897.449881
min,1.000000,1.000000,0.000000,-38.164920,144.542370,0.000000,1196.000000,0.000000
25%,2.000000,1.000000,91.000000,-37.855438,144.926198,5.900000,1940.000000,152.000000
50%,3.000000,1.000000,124.000000,-37.802250,144.995800,9.000000,1970.000000,373.000000
75%,4.000000,2.000000,170.000000,-37.758200,145.052700,12.400000,2000.000000,628.000000
max,8.000000,8.000000,3112.000000,-37.457090,145.526350,47.400000,2018.000000,37000.000000

In [11]:
x.head()

,Rooms,Bathroom,BuildingArea,Lattitude,Longtitude,Distance,YearBuilt,Landsize
1,2,1.0,79.0,-37.8079,144.9934,2.5,1900.0,156.0
2,3,2.0,150.0,-37.8093,144.9944,2.5,1900.0,134.0
4,4,1.0,142.0,-37.8072,144.9941,2.5,2014.0,120.0
6,3,2.0,210.0,-37.8024,144.9993,2.5,1910.0,245.0
7,2,1.0,107.0,-37.8060,144.9954,2.5,1890.0,256.0

In [12]:
from sklearn.tree import DecisionTreeRegressor
data_model = DecisionTreeRegressor(random_state=1)

# Using train test split

In [13]:
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

In [14]:
train_x, val_x, train_y, val_y = train_test_split (x,y,random_state=0)

In [15]:
data_model.fit (train_x,train_y)

DecisionTreeRegressor(random_state=1)

In [16]:
# getting predictions
prediction = data_model.predict(val_x)
print (mean_absolute_error(val_y, prediction ))

250241.93156875402

# Loop to compare different models using mean absolute error

In [17]:
def get_mae(max_nodes, train_x,val_x, train_y, val_y):
    data_model = DecisionTreeRegressor(max_leaf_nodes=max_nodes,random_state=0)
    data_model.fit(train_x,train_y)
    predict = data_model.predict(val_x)
    mae = mean_absolute_error(val_y, predict)
    return (mae)

In [18]:
for max_nodes in [5,50,500,5000]:
    mae_numbers = get_mae(max_nodes,train_x,val_x,train_y,val_y)
    print("max_leaf_nodes: %d \t\t Mean_absolute_error: %d" %(max_nodes,mae_numbers) )

max_leaf_nodes: 5 		 Mean_absolute_error: 347380
max_leaf_nodes: 50 		 Mean_absolute_error: 253257
max_leaf_nodes: 500 		 Mean_absolute_error: 239934
max_leaf_nodes: 5000 		 Mean_absolute_error: 248540

# Using Random_forest_regressor

In [19]:
from sklearn.ensemble import RandomForestRegressor
forest_model = RandomForestRegressor (random_state=1)
forest_model.fit(train_x,train_y)
for_preds = forest_model.predict(val_x)
print (mean_absolute_error(val_y,for_preds))

181932.77108057428

## using loops to compare Random forest model by changing parameters

In [20]:
model_1 = RandomForestRegressor (n_estimators= 50 ,max_depth=1, random_state =0, max_leaf_nodes= 5)
model_2 = RandomForestRegressor (n_estimators=100, max_depth=2,random_state=0, max_leaf_nodes= 4)
model_3 = RandomForestRegressor (n_estimators= 200,max_depth=4,  criterion='mse', random_state=0, max_leaf_nodes= 3)
model_4 = RandomForestRegressor (n_estimators=1, max_depth=5, criterion='mae',random_state=0, max_leaf_nodes= 2)
model_5 = RandomForestRegressor (n_estimators=100, max_depth=10, min_samples_split=20, random_state=0, max_leaf_nodes= 50)
model_6 = RandomForestRegressor (n_estimators=100, max_depth=7, random_state=0, max_leaf_nodes= 5000)

models = [model_1, model_2, model_3 , model_4 , model_5 , model_6]

def to_check(model, train_x,val_x, train_y, val_y):
    model.fit(train_x,train_y)
    preds = forest_model.predict(val_x)
    print(preds)
    print (val_y)
    return mean_absolute_error (preds,val_y)

In [21]:
for i in range (0,len(models)):
    mae2 = to_check(models[1],train_x,val_x,train_y,val_y)
    print('model %d \t\t mae %d' %(i+1,mae2))

[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 1 		 mae 181932
[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 2 		 mae 181932
[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 3 		 mae 181932
[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 4 		 mae 181932
[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 5 		 mae 181932
[ 970755.   537565.1  975605.  ...  244125.  1225850.  1815160. ]
4850      815000.0
2307      655000.0
10090     957500.0
3645     1330000.0
4930      722000.0
           ...
8223      520000.0
11190     870000.0
8563      200000.0
1867     1002000.0
8375     1710000.0
Name: Price, Length: 1549, dtype: float64
model 6 		 mae 181932

In [22]:
output = pd.DataFrame({'Id': val_y.index,
                       'SalePrice': for_preds})
output.to_csv('submission.csv', index=False)